WebApp/Models/Department.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Drawing;

namespace WebApp.Models
{
    public class Department
    {
        public int DepartmentID { get; set; }
        [Required(ErrorMessage = "Please enter the department name")]
        /*the user is required to enter the department name*/
        [Display(Name = "Department Name")]
        /*the name "Department Name" will be displayed like this in the forms and tables in the app*/
        [MaxLength(30, ErrorMessage ="the department name will have no more than 30 characters")]
        /*the department name will have the max length of 30 characters*/
        [MinLength(3, ErrorMessage ="the department name will at least 5 character")]
        /*the department name should have the minimum length of 3 characters*/
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "No numbers and symbols")]
        /*this regular expression should prevent the user from creating a last name contanting numbers and symbols*/
        public string DepartmentName { get; set; }
        /*fix this. I dont think I did relationships properly---->*/
        public ICollection<Staff> Staffs { get; set;}
        public ICollection<Subject> Subjects { get; set; }
        /*ImageName will be the title where the image link will be under in the department table*/
        public string ImageName { get; set; }
        [NotMapped]
        /*'ImageFile' wont have its own column in the department table*/
        [DisplayName("Upload File")]
        /*'Upload File' will be displayed in the create/edit/detail form instead of ImageFile*/
        public IFormFile ImageFile { get; set; }
    }
}

WebApp/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Areas.Identity.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly WebAppDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public DepartmentsController(WebAppDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        // GET: Departments
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            /*this is for paging. if a search is done, the page will reset to the number 1*/
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            /*select from the department table*/
            var departments = from t in _context.Department
                           select t;
            if (!String.IsNullOrEmpty(searchString))
                /*this is searching for the department name containing
                 * whatever name the user enters */
            {
                departments = departments.Where(s => s.DepartmentName.Contains(searchString));

            }
            switch (sortOrder)
                /*this is sorting, the department name is sort in descending order*/
            {
                case "name_desc":
                    departments = departments.OrderByDescending(t => t.DepartmentName);
                    break;
                    /*the default sort order is te order where I have created the departments in and
                     * it is not descending or ascending*/
                default:
                    departments = departments.OrderBy(s => s.DepartmentName);
                    break;
            }
            /*the maximum department displayed on 1 page will be 4*/
            int pageSize = 4;
            return View(await PaginatedList<Department>.CreateAsync(departments.AsNoTracking(), pageNumber ?? 1, pageSize));
            return View(departments.ToList());
            return _context.Department != null ?
                        View(await _context.Department.ToListAsync()) :
                        Problem("Entity set 'WebAppDbContext.Department'  is null.");
        }

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Department == null)
            {
                return NotFound();
            }

            var department = await _context.Department
                .FirstOrDefaultAsync(m => m.DepartmentID == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // GET: Departments/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DepartmentID,DepartmentName,ImageFile")] Department department)
        {
            if (!ModelState.IsValid)
            {
                /*the uploaded images will be saved in the wwwroot- image folder*/
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(department.ImageFile.FileName);
                string extension = Path.GetExtension(department.ImageFile.FileName);
                department.ImageName = fileName = fileName + DateTime.Now.ToString("yymmssffff") + extension;
                string path = Path.Combine(wwwRootPath + "/images", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await department.ImageFile.CopyToAsync(fileStream);
                }

                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Department == null)
            {
                return NotFound();
            }

            var department = await _context.Department.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DepartmentID,DepartmentName")] Department department)
        {
            if (id != department.DepartmentID)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.DepartmentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Department == null)
            {
                return NotFound();
            }

            var department = await _context.Department
                .FirstOrDefaultAsync(m => m.DepartmentID == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Department == null)
            {
                return Problem("Entity set 'WebAppDbContext.Department'  is null.");
            }
            var department = await _context.Department.FindAsync(id);
            if (department != null)
            {
                _context.Department.Remove(department);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
            return (_context.Department?.Any(e => e.DepartmentID == id)).GetValueOrDefault();
        }
    }
}

WebApp/Views/Departments/Create.cshtml
@model WebApp.Models.Department

@{
    ViewData["Title"] = "Create";
}

<h1 class=" info">Create</h1>

<h4>Department</h4>
<hr />
<div class="row info">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label>
                <input asp-for="DepartmentName" class="form-control" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" accept="image/*" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApp/Views/Departments/Delete.cshtml
@model WebApp.Models.Department

@{
    ViewData["Title"] = "Delete";
}

<h1 class ="info">Delete</h1>

<h3 class="info">Are you sure you want to delete this?</h3>
<div>
    <h4 class=" info">Department</h4>
    <hr />
    <dl class="row info">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DepartmentID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp/Views/Departments/Details.cshtml
@model WebApp.Models.Department

@{
    ViewData["Title"] = "Details";
}

<h1 class =" info">Details</h1>

<div>
    <h4 class=" info">Department</h4>
    <hr />
    <dl class="row info">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.DepartmentID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApp/Views/Departments/Edit.cshtml
@model WebApp.Models.Department

@{
    ViewData["Title"] = "Edit";
}

<h1 class=" info">Edit</h1>

<h4 class=" info">Department</h4>
<hr />
<div class="row info">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DepartmentID" />
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label>
                <input asp-for="DepartmentName" class="form-control" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" accept="image/*" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApp/Views/Departments/Index.cshtml
@model PaginatedList<WebApp.Models.Department>
    <!--reference to the PaginatedList model created for paging-->
@{
    ViewData["Title"] = "Department";
}

<h1 class=" info">Department List</h1>
<!--this class="info" will change the text colour white because the background is black-->

<p>
    <a asp-action="Create">Create New</a>
    <!--this is the button goes to the create form-->
</p>
@using (Html.BeginForm("Index", "Departments", FormMethod.Get))
{
    <p class="info">
        Search for department: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <!--search box/ this will make a box where the user can enter whatever they want to search-->
        <input type="submit" value="Search" />
        <!--this will submit whatever the user is searching-->
        <a asp-action="Index">Back to Full List</a>
        <!--the text "Back to Full List" will be the link to reset the search-->
    </p>
}
<!--grab the order by feature into a link from the table and place it above the cards--> 
<p class="info">
    Order by
    @Html.ActionLink("Department Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
</p>

<!--to hide the table-->
<table hidden class="table">
    <thead>
        <tr>
            <th>
                @Html.ActionLink("Department Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <!--this will be the name of the column and the link to sort the department name in descending order-->
            <th>
                Picture
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentName)
            </td>
                <td>
                    <img src="@("~/images/"+item.ImageName)" asp-append-version="true" width="75px" height="75px" />
                </td> 
                <!--this will give the user the option to upload an image. 
                                    The image will appear 75px width and height, will be saved under ImageName in the department table-->
            <td>
                <a asp-action="Edit" asp-route-id="@item.DepartmentID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.DepartmentID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.DepartmentID">Delete</a>
            </td>
        </tr>
}
        <!--cards= each card created for the staff it will be filled in rows and it repeats.-->
        <div class="flex-container">
            @foreach (var items in Model)
            {
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top image-card" src="@("~/images/"+items.ImageName)" asp-append-version="true" alt="Department image" style="object-fit: cover;">
                    <div class="card-body">
                        <h5 class="card-title">
                            <!--it will display the department name under the image-->
                            @Html.DisplayFor(modelItem => items.DepartmentName)
                            
                        </h5>
                        
                    </div>
                </div>
            }
        </div>
    </tbody>
</table>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<!--paging button. The previous and next buttons,
if the previous or next page isnt available, that button will be disabled-->
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default gree info @prevDisabled">
   <!--the 'info'' class is there to change the text colour white.
    I noticed how the btn btn-default class makes it so when the user hovers over a button, 
    the button colour gets darker which is too similar to the text colour.
    I created the class 'gree' to chnage the text colour text when hover.-->
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default gree info @nextDisabled">
    Next
</a> 